### ISSUE TITLE
Que running during "rails generate" "rake db:migrate" (!!) and console

### ISSUE THREAD

**Issue by jasonl99** [chanks/que#109]
This has just started happening in the last few days.  It seems to me that running during a migration is not the best idea.  It also runs in the console unless setting Que.mode = :off.  I have a vague recollection of a doing setting a few months ago that turned it off in the console that seems to be no longer working.

Rails 4.2.1, ruby 2.2.2p95.

**Comment by chanks** [comment]
Ugh. The auto-startup logic in the Railtie has turned out to be way more
trouble than it's worth. I really think it's time to provide a
sidekiq-esque CLI, and if anyone wants to run the worker pool in the same
process it'll be up to them (or a separate gem) to figure out how to do so
safely.

Did you make any changes to the app when this started? The worker pool only
starts up by default when Rails::Server is defined, so I wonder whether you
recently added a gem or something that somehow causes the server to be
loaded every time the environment executes. Not that it would be wrong of
that other gem to do so or that Que shouldn't handle this better - I just
think it'd be useful information.

**Comment by jasonl99** [comment]
I just went through the last month's worth of changes to my Gemfile, and the only thing I've added is pundit (user authorization).  Is there any sort of tracing I can do to isolate where Que is getting enabled?

**Comment by jasonl99** [comment]
Quick update - my Gemfile.lock shows that rack went from 1.6 to 1.6.1 two days ago.  That seems about when this started happening.

**Comment by chanks** [comment]
Can you try booting your app before and after that change and see whether the behavior is different? If it's not, no big deal, don't spend too much time on it :)

**Comment by jasonl99** [comment]
I tried going back to 1.6.0, and that was not it.  Still happens in console and rake db:migrate.

**Comment by chanks** [comment]
Oh well, don't worry about it. For now, are you able to work around it by setting mode = :off in an initializer and just working jobs via the rake task?

I think my next goal for the gem will be to remove that auto-running functionality from the railtie, establish a simple CLI, see what other open issues I can resolve and release that as 0.11.0. I think I'll be able to get to all that in the next week or two, so long as you're able to get things working for the time being.

**Comment by jasonl99** [comment]
Thanks - yes, this is an app still in development (and Que has been HUGELY
useful for me, so a gigantic thanks to you).  If there's anything you want
me to debug, I'm more than happy to help.  Just let me know what you need.

**Comment by chanks** [comment]
No, problem, and thanks!

**Comment by chanks** [comment]
Hey @jasonl99 - I just opened a PR (#112) introducing a command line interface to replace the autostarting logic. If you're still struggling with this, try it out and let me know if you run into any problems? Thanks!

**Comment by jasonl99** [comment]
Thanks Chris,

I just updated to this one, and doing a quick test at the console, and a
"rake routes" seems to work great.

I use a pry console, so I had added an entry to my .pryrc file (Que.mode =
:off) to work around the issue before this version.  When I tried the #112
version, I got this message at startup:

{"lib":"que","hostname":"jason-Latitude-E5540","pid":15446,"thread":13744520,"event":"mode_change","value":"off"}

Once I removed the Que.mode = :off from .pryrc, it's clean.  I had no
troubles with rake commands generating any pry output.

I haven't yet figured out where to put Que.mode = :async for when rails
server.  Will get back to you in the next few days once I have a chance to
get it into the server.

**Comment by chanks** [comment]
Alright, cool. I don't know that there's a great general solution for how to get a background worker pool running in-process when rails is running as a server, but if you find one I'd be curious :)

(And it would probably make a good third-party gem, since I imagine it'd have to be versioned when Que changes as well as when Rails does.)

In the meantime I'm going to close this, since I think it's pretty well addressed by #112, but if you run into any more issues, please let me know!
