### ISSUE TITLE
Use ActiveSupport's constantize if it exists

### ISSUE THREAD

**Issue by joevandyk** [chanks/que#115]
```
$ rails c
Loading development environment (Rails 4.2.1)

irb(main):001:0> string = "Fulfiller::Jobs::SunFrog::SendOrders"
=> "Fulfiller::Jobs::SunFrog::SendOrders"

irb(main):002:0> string.split('::').inject(Object, &:const_get)
NameError: uninitialized constant SunFrog::SendOrders
	from (irb):2:in `const_get'
	from (irb):2:in `each'
	from (irb):2:in `inject'
	from (irb):2

irb(main):003:0> string.constantize
=> Fulfiller::Jobs::SunFrog::SendOrders
```

https://github.com/chanks/que/blob/master/lib/que/job.rb#L140 -- using const_get doesn't work perfectly with Rails's autoloading (I also have a top-level SunFrog constant).

**Comment by chanks** [comment]
Hmm, is this specific to something Rails does with autoloading, or will it fail with Ruby's autoloading as well? If it's the former, I think using constantize when available makes sense, but if it's the latter, it might make more sense to just copy over ActiveSupport's constantize implementation so that it works for people not using ActiveSupport too.

**Comment by joevandyk** [comment]
Probably worth bringing in their implementation. 

https://github.com/rails/rails/blob/4-2-stable/activesupport/lib/active_support/inflector/methods.rb#L250-L279

**Comment by chanks** [comment]
Alright, I'd accept a PR that does that, or I'll try to get to it when I
next have time. I think the time consuming part will be the specs.

**Comment by joevandyk** [comment]
I'll take a stab at it during lunch today.

**Comment by joevandyk** [comment]
https://github.com/chanks/que/pull/120
