### ISSUE TITLE
Que keeps logging job_unavailable instead of doing its job

### ISSUE THREAD

**Issue by mspanc** [chanks/que#124]
I keep getting

``` 
{"lib":"que","hostname":"df7fcecc-24b6-405b-899a-0ca294f09637","pid":6,"thread":70002836492360,"event":"job_unavailable"}
```

in the error log. The jobs are not launched.

Running my app on heroku with unicorn.

Added `Que.mode = :async` after establishing DB connection in unicorn starter script.

Some debug info:

```
irb(main):004:0> Que.execute("select count(*) from que_jobs")
=> [{"count"=>3}]
irb(main):005:0> Que.job_stats
=> [{"queue"=>"default", "job_class"=>"ActiveJob::QueueAdapters::QueAdapter::JobWrapper", "count"=>3, "count_working"=>0, "count_errored"=>0, "highest_error_count"=>0, "oldest_run_at"=>2015-09-22 04:52:02 +0000}]
```

DB dump

```
> select * from que_jobs;
 priority |            run_at             | job_id |                    job_class                     |                                                                                          args                                                                                           | error_count | last_error |  queue
----------+-------------------------------+--------+--------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------+------------+---------
      100 | 2015-09-22 04:52:02.720106+00 |     90 | ActiveJob::QueueAdapters::QueAdapter::JobWrapper | [{"job_class":"ChannelMedatatumCoverArtJob","job_id":"54641e0e-b226-4eb9-9d60-6d91a232be59","queue_name":"default","arguments":["b65df816-69a0-441c-bd6e-ae0a539b6b63"],"locale":"en"}] |           0 |            | default
      100 | 2015-09-22 04:52:18.360613+00 |     91 | ActiveJob::QueueAdapters::QueAdapter::JobWrapper | [{"job_class":"ChannelMedatatumCoverArtJob","job_id":"596c03d1-ef9f-4c83-8872-366e636ec24c","queue_name":"default","arguments":["3394a021-c1ea-46a9-bc37-934c334c1e53"],"locale":"en"}] |           0 |            | default
      100 | 2015-09-22 04:52:39.149772+00 |     92 | ActiveJob::QueueAdapters::QueAdapter::JobWrapper | [{"job_class":"ChannelMedatatumCoverArtJob","job_id":"bee4fad9-3a22-4695-b98d-53508cd13fc4","queue_name":"default","arguments":["d81c7dc8-b61b-4783-a878-817a72727bef"],"locale":"en"}] |           0 |            | default
      100 | 2015-09-22 04:55:09.047588+00 |     93 | ActiveJob::QueueAdapters::QueAdapter::JobWrapper | [{"job_class":"ChannelMedatatumCoverArtJob","job_id":"7541030d-138e-4eea-9a21-0647fee22d84","queue_name":"default","arguments":["06673e53-66cc-4705-976e-e7a61501eeaa"],"locale":"en"}] |           0 |            | default
(4 rows)
```

Job code

```ruby
class ChannelMedatatumCoverArtJob < ActiveJob::Base
  def perform(channel_metadatum_id)
    Channel::Metadatum.transaction do
      begin
        metadatum = Channel::Metadatum.find(channel_metadatum_id)

        if metadatum.kind == "music" and metadatum.music_cover_art_url.blank?
          metadatum.music_cover_art_url = Utils::Discogs.new(metadatum.music_artist, metadatum.music_album).image_url
          
          if metadatum.music_cover_art_url.blank?
            metadatum.music_cover_art_state = "not-found"
          else
            metadatum.music_cover_art_state = "found"
          end

          metadatum.save!
        end

      rescue
        metadatum.music_cover_art_state = "error"
        metadatum.save!
      end
    end
  end
end
```

Tried to set QUE_QUEUE=default via env vars - no success.

Running jobs via `rake que:work` works OK but I want to run them within unicorn.

que 0.11.2
ruby 2.2.3
rails 4.2.4 
unicorn 4.9.0

Regardless of what is the exact reason behind this, there's no single info in the que docs about this type of error message.

**Comment by chanks** [comment]
There's no info in the docs about it because there's not a known common reason why it would happen :smile: And in fact I don't know offhand why you're getting it. You'll get job_unavailable if the job locking query can't find any jobs that are ready to work, but it doesn't look like that should be the case.

I notice you're using ActiveJob, are you using it to set a time for the job to run? Que uses the database's clock to determine whether it's time for a job to run. There's not enough information for me to tell from what you've written, but my first guess would be some kind of time-related issue in either your application or DB, maybe involving whatever your time zone is.

You can also learn more by running the job lock query yourself (see the recursive CTE in sql.rb) and seeing whether it returns any rows, or whether it starts once you remove some of the conditions in it. That'll start narrowing things down.

**Comment by mspanc** [comment]
I am just using `MyJob.perform_later arg` syntax. But I tried to use raw Que methods and the issue was the same. 

I had not switched any time zones or any other significant configuration. The app is really simple,  plain RoR app with a few simple models, run on standard heroku environment. 

I am unable to dig into that issue any more, I had to proceed and switched the backend to socker punch.

**Comment by chanks** [comment]
Alright, sorry it didn't work for you.

**Comment by chanks** [comment]
If anyone else has similar symptoms, btw, please bring them up!

**Comment by impurist** [comment]
I experienced this a few days back. (running 0.8.1)
Thanks to your suggestion of running the raw SQL job lock query I could see the job was created with 
a queue name because job class has the line 
"queue_as :collection_sync_job"
 whereas the config and thus the query was looking for an empty string where the queue value was '_collection_sync_job' and thus never returned the job.
Solution:
I removed the line above and let it use the default queue name 'active_jobs'
Upgraded que to 0.11.2
Adjusted the initialiser  to use  'active_jobs'
All working.

**Comment by chanks** [comment]
Thanks, good to know!

**Comment by lessless** [comment]
I'm getting this message right after installing  0.12, did nothing except  just opened rails console.

**Comment by lessless** [comment]
Hello,
getting same error in fresh 0.12 install: `{"lib":"que","hostname":"localhost","pid":6101,"thread":70269362725740,"event":"job_unavailable"}`

database log:

```
ostgresql_1     | ERROR:  relation "que_jobs" does not exist at character 147
postgresql_1     | STATEMENT:
postgresql_1     | 	      WITH RECURSIVE jobs AS (
postgresql_1     | 	        SELECT (j).*, pg_try_advisory_lock((j).job_id) AS locked
postgresql_1     | 	        FROM (
postgresql_1     | 	          SELECT j
postgresql_1     | 	          FROM que_jobs AS j
postgresql_1     | 	          WHERE queue = $1::text
postgresql_1     | 	          AND run_at <= now()
postgresql_1     | 	          ORDER BY priority, run_at, job_id
postgresql_1     | 	          LIMIT 1
postgresql_1     | 	        ) AS t1
postgresql_1     | 	        UNION ALL (
postgresql_1     | 	          SELECT (j).*, pg_try_advisory_lock((j).job_id) AS locked
postgresql_1     | 	          FROM (
postgresql_1     | 	            SELECT (
postgresql_1     | 	              SELECT j
postgresql_1     | 	              FROM que_jobs AS j
postgresql_1     | 	              WHERE queue = $1::text
postgresql_1     | 	              AND run_at <= now()
postgresql_1     | 	              AND (priority, run_at, job_id) > (jobs.priority, jobs.run_at, jobs.job_id)
postgresql_1     | 	              ORDER BY priority, run_at, job_id
postgresql_1     | 	              LIMIT 1
postgresql_1     | 	            ) AS j
postgresql_1     | 	            FROM jobs
postgresql_1     | 	            WHERE jobs.job_id IS NOT NULL
postgresql_1     | 	            LIMIT 1
postgresql_1     | 	          ) AS t1
postgresql_1     | 	        )
postgresql_1     | 	      )
postgresql_1     | 	      SELECT queue, priority, run_at, job_id, job_class, args, error_count
postgresql_1     | 	      FROM jobs
postgresql_1     | 	      WHERE locked
postgresql_1     | 	      LIMIT 1
postgresql_1     |
```

PG 9.5, Rails 4.2.7.1, table does exist: 

```
app_development=# \d que_jobs
                                      Table "public.que_jobs"
   Column    |           Type           |                         Modifiers
-------------+--------------------------+-----------------------------------------------------------
 priority    | smallint                 | not null default 100
 run_at      | timestamp with time zone | not null default now()
 job_id      | bigint                   | not null default nextval('que_jobs_job_id_seq'::regclass)
 job_class   | text                     | not null
 args        | json                     | not null default '[]'::json
 error_count | integer                  | not null default 0
 last_error  | text                     |
 queue       | text                     | not null default ''::text
Indexes:
    "que_jobs_pkey" PRIMARY KEY, btree (queue, priority, run_at, job_id)
```

**Comment by chanks** [comment]
Oops, was responding to the email but I see you edited your post so that
response doesn't make sense :)

So, there used to be logic to try to start Que in a certain mode in
different Rails contexts (off in the console and rake tasks, on in the
server) but I removed it because it was too dependent on Rails internals
and kept causing problems. Now, Que only starts when you tell it to, and
should usually be run via the executable. So, I suspect you're setting
Que.mode = :async in an initializer? So if you want to do things that way
that's fine, but it'll be your responsibility to make sure that that logic
doesn't run in the console.

Also, where did you see that it wouldn't start up in the console? That's
old information and should be fixed.
