### ISSUE TITLE
Worker feature request: only work certain priority jobs

### ISSUE THREAD

**Issue by cpence** [chanks/que#126]
Hello!

I'm putting together a text analysis system that extensively uses Que background jobs. Trouble is, some of them will take possibly as long as days, some only minutes, and some are triggered by UI events and need to be worked ASAP.

Here's the problem -- if I have five Que workers, say, and all five of them get bound up processing days-long analysis jobs (because no short jobs happen to be available at the moment), all of a sudden I have no workers to work my more important jobs.

Based on the discussion in #71, it's pretty clear that named queues are *not* how you'd like end-users to deal with this kind of thing. It seems like priorities are correct. But in that case, I'd *really* like a command-line option to `que` that lets me say "work only jobs between priorities X and Y." That way I can do something like:

```
# Start two workers to work "low-priority" analysis jobs
que --worker-count 2 --min-priority 1 --max-priority 99 ./config/environment.rb
# Start two workers to work "high-priority" UI jobs
que --worker-count 2 --min-priority 100 --max-priority 999 ./config/environment.rb
```

Is that something you'd consider adding? If so, I could look at putting a pull request together. I just wanted to gauge how you thought I should solve the kind of use case I have here.

**Comment by chanks** [comment]
So, having pools of workers with differing priorities is something I've already tackled in the 1.0 branch. You can explicitly spin up workers with priorities [10, 20, 30, 40, 50] for example. Then, if you have a bunch of long-running jobs with priority 30, they'll be worked on by your [30, 40, 50] workers, and your [10, 20] workers will still be listening for more important jobs to come along. I think this solves your problem (in addition, 1.0 uses LISTEN/NOTIFY instead of polling and has other benefits).

That said, relying on the 1.0 branch isn't the greatest idea, because A) I don't have a ton of time to work on it and B) it's currently in a rather unusable state, since I was trying to revamp things to support multiple job queues (that is, truly distinct queues, in different tables) when I last left off.

So as for what's best for you to do, I'm not sure. I think you could probably support a priority range without much work, but it's not really going to match where the gem is going, so it's probably not worth the trouble to turn it into a PR. On the other hand, it'd probably be a good idea for me to release 1.0 soon (it was in a pretty good state before I started trying to add multiple queues to it, I could start working towards releasing that, and the multiple queues feature could always wait for a later release). On the other hand, if you want a quicker solution, you could certainly just start with the multiple queues now and migrate off of it later. You won't be the only one, and I don't think the migration will be too intimidating.

**Comment by cpence** [comment]
That sounds good. At the moment I'm using Que 0.x through ActiveJob in Rails 4, which has support for multiple named queues. Hopefully by the time Rails 5 rolls around, I can switch to Que 1.x and new ActiveJob, which loses support for multiple queues but gains support for priorities, so it all will cancel out in the end.

Thanks! Excited to see Que 1.0 when it shows up!

**Comment by chanks** [comment]
Ok. I submitted a patch to ActiveJob to remove support for named queues in the Que adapter, and it was accepted but I don't know what release it'll end up in. I was trying to get people off of named queues in the standard case since I think most people should not be using them.

In general, if you're going to be relying very heavily on the behavior and characteristics of your job queue, I wouldn't recommend using ActiveJob, I think it tries to abstract away too much.

**Comment by cpence** [comment]
For now it can do everything I need, though that may wind up becoming false someday. Worst-case I can pin ActiveJob at a version with multiple queue support and unpin when Que 1.0 hits.

**Comment by kbrock** [comment]
FWIW/ On two other projects, I had the same need for processing workloads that take a short and long time. One used resque and the named queues worked great. Another system used delayed job and priority number ranges. The numbers felt a bit like a hack, but it worked well enough.

Right now, I'm looking into converting from a custom postgres queue system to que. This will be fun. 

Thanks for all the hard work.
