### ISSUE TITLE
Improvements to development env?

### ISSUE THREAD

**Issue by dts** [chanks/que#170]
I'm working on a complex job that I am having to retry frequently as I fix minor bugs along the way.  My current process is quitting & relaunching the `que` binary and using the rails console to set run_at to now, so I can trigger the job running immediately.  It would be awesome if the que binary honored the configurations for class cache clearing & reloading.

**Comment by jeffling** [comment]
If you're working on a job like that, you might as well run the job synchronously using Que.mode = :sync

**Comment by chanks** [comment]
Closing out old issues. I've never had this problem, I suppose because I develop jobs in a TDD-ish way rather than actually running them alongside the server (I think this is the more common method as well). That said, more recent versions of Que use Rails' application executor API, which is used to protect code reloading. So it's possible that this is no longer an issue anymore.

If you try using the 1.0 beta and are still running into problems with this, please reopen the issue and we can try to figure something out.
