### ISSUE TITLE
Change migrations to be AR methods

### ISSUE THREAD

**Issue by avinoth** [chanks/que#172]
Currently `que` uses custom method to create the migration file instead of standard AR methods, so in case of moving away from que, it's difficult to rollback them except to manually delete it and updating the schema_migrations.

It could be better if que used normal AR methods to create the tables or an API in que to rollback the migration.

**Comment by avinoth** [comment]
Or we could have the migration as normal AR methods similar to how Devise generates. Another option is we could have a command to create a down migration maybe?

**Comment by chanks** [comment]
Last I checked, ActiveRecord didn't have support for composite primary keys
or function defaults for columns, both of which Que uses, so I don't think
it's possible to use ActiveRecord migration methods. We could have people
use the raw SQL in their migrations, but I'm not a fan of the idea of
generating ActiveRecord migrations, since I'm trying to get away from
tighter integration with Rails in general.

**Comment by avinoth** [comment]
I understand. giving users raw SQL is same as handling it in Que's end itself, but if the plan is to be framework agnostic then it's the only way and let users to do the migration themselves.

**Comment by chanks** [comment]
Closing some old issues. If someone wants to move off of Que, I think it's reasonable to just use the built-in method to do that (migrate to version 0, as described in the docs). If you want to then remove Que as a dependency you can then just comment out all the `Que.migrate` lines in the old migrations (I know editing migrations is kind of taboo, but in this case it should be harmless).
