### ISSUE TITLE
Missing queue name in Rails 5

### ISSUE THREAD

**Issue by dmkl** [chanks/que#179]
After migration to Rails 5 job record is created with blank `queue` field (via ActiveJob) and worker doesn't pick it up. Jobs stay unprocessed. Why was explicit queue param removed https://github.com/rails/rails/commit/fdfca02c304d809aac53ebf8094b237d0ba6415e?  Does it require any additional ActiveJob config on top of `queue_as :my_queue_name` to get it working?

**Comment by dmkl** [comment]
@chanks is it a correct fix for this issue https://github.com/dmkl/que/commit/a258459f15a09d0983e057bbd2779d3d964e49fb?

**Comment by chanks** [comment]
I originally removed named queue support from ActiveJob because people were using it for priorities, when Que already has an integer-based priority system that's more efficient for querying. Now I think this was a mistake on my part - people have brought up use cases where they need named queues that aren't priorities.

If that fix helps you work with Rails 5, that's great, but I don't think that abusing the args hash like that is a good idea in general. I think we should try to re-add support for named queues to the ActiveJob adapter instead, though I would encourage you to only use named queues if you really need them (you need different jobs to be processed by different codebases, or by application instances running with different resources, for example).

**Comment by joevandyk** [comment]
@chanks btw it would be super duper awesome if workers could specify 0, 1, or many queues to listen on.  In production I might want to have workers dedicated to each queue, but in dev or staging I might not. I believe sidekiq and resque support this.
