### ISSUE TITLE
Question: Alternative to multiple queues

### ISSUE THREAD

**Issue by harukizaemon** [chanks/que#186]
I see that the intention is to remove support for multiple queues in 1.0 and I totally understand the rationale for this.

I have a situation where I have been using distinct queues to manage distinct resources. So I have workers assigned for each of the resources - eg CPU-bound jobs, GPU-bound jobs, jobs that require a specific piece of scientific equipment, etc.

This is different to prioritisation in that all of those classes of job can run concurrently but how many of each class can run - and in what order - is an orthogonal concern.

Should I be looking to use a different queueing library, or is this a use case you can envisage continuing to support somehow?

Regards,

Simon

**Comment by chanks** [comment]
Yeah, multiple queues was something I wanted to remove at one point because I felt like people were using them to implement priorities, Sidekiq-style, when that's not really the optimal use case. But enough people have had other use cases for them (like yours) that I've started to feel that they serve an important purpose. So you can be confident that they'll stick around :smile:

**Comment by bjeanes** [comment]
@chanks given your above comment, are you now also open to evolving Que to officially support workers pulling from multiple queues as per #71?

FWIW, my chief named queue use-case is as @harukizaemon described; I have batch importer jobs which require a lot more RAM than most jobs. Furthermore, these jobs also typically run for 30 minutes to hours. Keeping those jobs out of general queues (regardless of their priority) is critical to keep job processing latency down.

Another use-case I've faced recently is needing to tune the parallelism factor of different types of jobs. For example, a spike in certain types of activity might demand processing them with more workers, but allowing other job types to implicitly become more concurrent may have negative implications (e.g. they may hit the DB harder so having a lot of them potentially enqueue at the same time is an operational risk).

I've been following along on all the named queue issues but haven't seen an update on your thinking recently. I used Que a lot at Heroku and really miss it, but my current job has pretty hard requirements on these use-cases and so I'm still stuck on Delayed::Job until then...

**Comment by chanks** [comment]
Yeah, they're already implemented in the 1.0 branch, but I wouldn't recommend using it yet - that branch is basically a total rewrite and it's still in flux. I'm spending every one of my open-source Fridays at work (and also some off-hours) on it, though. I think it's probably a month or so away from an alpha release.

**Comment by chanks** [comment]
Also, just so I understand your use case, how does one worker running
multiple queues help you? Is your plan to run some workers on just the
general queue, to make sure it's latency is always low, and then have other
workers pull from both queues, so that they're still able to help out with
the general queue when there aren't any batch jobs?

**Comment by bjeanes** [comment]
That's exactly right, for one use-case (arguably less important).

That is, at a high-level, there are transactional jobs (many, short-lived) and batch jobs (fewer, long-running). The batch jobs also _tend_ to require a lot more RAM or CPU just because of how much data they tend to load into memory at once. I do actually scale these down automatically when we don't have batch jobs queued, but I always keep a few on stand-by to start processing immediately (while others start up to be on stand-by). The stand-by ones I have also pulling transactional work when they would otherwise be idle.

Now, others have mentioned wanting to preference one queue over another, but I agree with your general stance here that queues are orthogonal to priorities. I'd design for this case by having those batch jobs higher priority but always having transactional workers that exclude batch work.

The other use-case for workers listening to multiple queues is more critical to the architecture I've described above. If you literally only had two queues (`transactional` and `batch`, say), then it would not be as important. However, if you have `transactional-a`, `transactional-b`, `batch-high-ram` (made-up), you'd need to specify that your transactional workers need to pull from `transactional-a` and `transactional-b`, hence needing to specify multiple queues.

To give more context into why there is multiple transactional at all, it's as I alluded above. Different items of work have different scaling semantics. Some you could _safely_ run 100x of the same work in parallel. Others perhaps you can only run 3-4x at a time without causing a performance issue (say a down-stream service). Therefore, it's important to be able to launch more workers that are only pulling a _subset_ of available work, so that you don't exceed a concurrency factor for other work.

So typically I have a smallish `N` of workers that are always ready to pick up any short-lived job. Then I have 0 or more workers that may listen to a single transactional queue and act somewhat elastically, with the elasticity factor somewhat queue dependent.

Does that make it clear? I'm happy to elaborate further in any way.

If I were designing a job system from scratch, I might not use queue names for these use-cases, actually, but this type of problem does need some kind of solution, I think. For instance, jobs could encode constraints ("i need lots of CPU", "I'll run for a while", "highly bandwidth network please", "avoid running more than N of me at a time please") and workers opt-in to certain constraints. I think that's in principle harder to get right than queue names, though.
