### ISSUE TITLE
[Architecture / SQL] What do you think of "skip locked" ?

### ISSUE THREAD

**Issue by kofronpi** [chanks/que#195]
I recently read a blog article claiming that most PostgreSQL queues implementations are wrong, and that those relying on advisory lock can "work well within limits" 
They also claim that you should use `skip locked` to build queues in pg.

Source: https://blog.2ndquadrant.com/what-is-select-skip-locked-for-in-postgresql-9-5/

In the comments section, there is something about a pg queue author in perl claiming perf gains of 30% since they use `skip locked`.

@chanks, can you read the article and tell me what you think ? :)

**Comment by chanks** [comment]
Yeah, I've read that article. I wrote my thoughts on SKIP LOCKED a while ago, I don't think anything has changed since then? See here: https://github.com/chanks/que/issues/158#issuecomment-225932045

The only major drawback I see in using advisory locks is that it could interfere with their use by other code, though I don't think that's ever been a problem in practice. And since advisory locks by the same connection stack (you can lock the same one twice, but you have to unlock it twice) I'm not sure it would be a showstopper even if something else did want to use advisory locks. I think the worst case scenario is that some code would be delayed unnecessarily. I may be wrong about that, though.

**Comment by kofronpi** [comment]
@chanks Sorry I've searched too quickly with bad keywords, so I didn't find the relevant issues. I'm gonna read all that, thanks !

**Comment by chanks** [comment]
No problem :smile: thanks for the interest! And if you have any great ideas, please let me know!
