### ISSUE TITLE
v1.0 status

### ISSUE THREAD

**Issue by patleb** [chanks/que#197]
Hi, I was wondering what is the status v1: is it ready for production or stable yet?

**Comment by chanks** [comment]
It's somewhat stable. It's been running in production at my day job for a few months. There have only been a couple of issues, and I've been fixing them as I go.

The main thing that's preventing me from releasing a 1.0.0.beta is that I'm not sure I'm done making tweaks to the new migration (number 4) yet :confused: It's a big and complex one, and I can't really make changes once it's been officially released.

**Comment by chanks** [comment]
Tell you what, though, if you're wanting to use it, I'll commit to
releasing 1.0.0.alpha (let's call it alpha, why not) in the next few days.
The remaining things on my investigation list mostly have to do with Rails
compatibility, which shouldn't require any schema changes. And of course
the documentation needs some work.

**Comment by patleb** [comment]
Thanks for your quick answer!

No need to rush it for me. Just knowing that it's somewhat stable and still maintained is good enough for me.

I'm planning to add queuing in a client project maybe by the end of the month. I discarded delayed_job (bad past experiences) as a candidate and would not need redis for anything else than Resque/Sidekiq. So Que seemed like the perfect candidate, I've use it 2 years ago and it was doing a good job.

**Comment by chanks** [comment]
Ha ha, ok, thanks. I'm going to put the alpha out soon, but if it's not out
by the time you need it, please let me know.

**Comment by patleb** [comment]
Got it, thanks :+1:

**Comment by chanks** [comment]
No problem! Gonna close this for now.

**Comment by patleb** [comment]
Hi @chanks, I'm gonna add a queue service this week to the project I was referring to and I would like to know if you think I should use v1.0, since I see that you're still working on it?

Also, just to let you know, if it goes well and time permits, I might give a shot at doing something similar to [sidekiq.cr](https://github.com/mperham/sidekiq.cr) for Que but only as a job consummer for crystal.

**Comment by chanks** [comment]
Hey there - yeah, I think you should I just want to spend a little time wrapping up a few specs and docs before I cut a 1.0.0.beta version. I'm unfortunately pretty busy tonight and tomorrow, but I could do it on Tuesday night, if that's soon enough for you?

Also, do you have a timeline for when you're wanting to release this to production? Because there's some behavior I've been running into (that I'm 95% sure is a bug in Postgres) and it probably wouldn't be a good idea to rely on it absolutely until that's ironed out.

**Comment by patleb** [comment]
I can add some functionnalities unrelated to Que while 1.0.0.beta is been finished, this is not a problem. I can delay until next week, maybe a little bit more, before writing something serious using Que. The delivery date for the complete system would be around the end of november/beginning of december.

Otherwise, glad to hear that I could use it, I'm eager to start the integration. Thanks!

**Comment by chanks** [comment]
Alright! It took me all night but I just pushed 1.0.0.beta to Rubygems.

You're kind of my experimental subject, so let me know what problems you encounter. I've been using it in a production app at my day job for a while, but this will be the first time anyone but me has really had to interact with it, so there may be sharp edges.

Also please make sure that when you peruse the docs you're on the 1.0 branch on Github, because a lot of the docs on the master branch don't apply anymore. And the docs certainly need some more attention, I'll be getting to that over the next week. In the meantime I'm here if you have questions.

Thanks!

**Comment by patleb** [comment]
Nice, thanks a lot, I'm finishing some stuff before, but I think I might be able to start the integration with Que this friday. I'll let you know how it goes.

**Comment by patleb** [comment]
Hi, just to let you know that the project that I was supposed to use Que has been delayed (and possibly will be canceled, in part), but I'm gonna use it from the get go on the next project.

**Comment by chanks** [comment]
Ah, alright, good to know. Thanks!

**Comment by 9mm** [comment]
Hey, just wanted to check in on...

1. This is a great thread, I'm excited about the new release. What is the new status of `1.0.0`?

2. What are the main benefits/improvements/changes over the current stable?

3. How are the performance improvements? I want to use it on a new app which has millions of jobs, but I can't use Sidekiq because I need the excellent guarantees of PG (its financial related)

**Comment by chanks** [comment]
I’m working on 1.0 as I have free time. The beta is used in production at
my day job (pathgather.com).

For a comprehensive list of changes see the changelog in the 1.0 branch.

I expect that for a given DB instance the performance in 1.0 will be better
than 0.x, but the throughput will generally be dependent on what kind of
hardware you run your DB on. If you have high performance requirements I’d
recommend testing it out first.

**Comment by 9mm** [comment]
Oh that changelog is perfect, thanks... I didn't see that. I dunno if you have time, but I had this issue here when trying to install it earlier today:

https://github.com/chanks/que/issues/206

**Comment by chanks** [comment]
Yeah, I didn’t want to respond until I had time to look into it. There’s
pretty thorough specs for the Rails interactions so far as ActiveJob,
ActiveRecord and ActiveSupport, but Railtie issues are hard to test.
