### ISSUE TITLE
undefined method `run_asynchronously=' for Que:Module

### ISSUE THREAD

**Issue by bgentry** [chanks/que#214]
[This line](https://github.com/chanks/que/blob/fb94321b40f763fb48db1a63f0c1084bee961388/lib/que/rails/railtie.rb#L8) calls a function `Que.run_asynchronously=` that doesn't exist.

**Comment by bgentry** [comment]
It looks like that Railtie is meant to disable synchronous run, so maybe it should just be `Que.run_synchronously = false`?

**Comment by chanks** [comment]
Ugh, thanks for pointing that out. This is what I get for having untested code :disappointed: 

I just pushed a commit to remove it, since I think that the better approach these days is to insert jobs and then assert on their representation in the DB. People can still set run_synchronously on a case by case basis if they want it, though.

**Comment by bgentry** [comment]
> I just pushed a commit to remove it, since I think that the better approach these days is to insert jobs and then assert on their representation in the DB. People can still set run_synchronously on a case by case basis if they want it, though.

I agree, this is what I've always done 😄
