### ISSUE TITLE
Migration to version 4 : function public.que_validate_tags(jsonb) does not exist

### ISSUE THREAD

**Issue by kofronpi** [chanks/que#219]
Hi,
I'm using postgres 9.5 and postgres 10.3 on different servers with que.
I'm using rails 5.1.6, ruby 2.4.4 and que 1.0.0.beta3 

When attempting to migrate to the 4th version of que's schema on my pg cluster 9.5, I get this error: 

```
rails aborted!
StandardError: An error has occurred, this and all later migrations canceled:
ERROR:  function public.que_validate_tags(jsonb) does not exist
```

My migration file:

```
class MigrateQue < ActiveRecord::Migration[5.1]
  def self.up
    Que.migrate! version: 4
  end

  def self.down
    Que.migrate! version: 3
  end
end
```

Any idea ? thanks :)

**Comment by kofronpi** [comment]
@chanks I do have other schemas, but que_jobs is in `public`.

**Comment by chanks** [comment]
Hmm, ok. That's weird, because the migration file (https://github.com/chanks/que/blob/master/lib/que/migrations/4/up.sql) defines that function before adding the check constraint that uses it. I see how it could fail if the script were being executed in a non-public search path...

The next thing I'd suggest is to try changing your migration to execute that script one piece at a time and see exactly where it fails - I suspect it's in the `ADD CONSTRAINT valid_data` part of the main `ALTER TABLE`, but it'd be nice to confirm that. Then, before reaching that point, try inspecting the pg_proc table (https://www.postgresql.org/docs/10/static/catalog-pg-proc.html), probably in a debugger within your migration (so you're inside the transaction), and figure out if `que_validate_tags` is getting defined. I think this will look something like `ActiveRecord::Base.connection.execute("SELECT * FROM pg_proc WHERE proname = 'que_validate_tags';").to_a`, but I haven't used Rails 5+ myself, so I may be wrong.

**Comment by kofronpi** [comment]
@chanks  Spot on ! `public` was not first in the search_path by default in `config/database.yml`. I've changed it to be first there, but I need to check out if it may have side-effects on my app. Thanks, I am closing this for now.

**Comment by chanks** [comment]
Cool! Glad it worked out :smile:
