### ISSUE TITLE
Pass whole job object to error_notifier?

### ISSUE THREAD

**Issue by timriley** [chanks/que#220]
Hi @chanks —

We use Que across all our apps at Icelab (and it is great, thank you!), and in my current project I am trying to do some manual integration of Que with an error tracking service. By manual, I mean: rather than simply using their gem's out-of-the-box Que integration (which is all monkey patching), I want to add some extra methods to our app's own base job class (which inherits from `Que::Job`, and from which all our other application jobs inherit) to expose the various pieces of information that the error tracker will want to receive, and then use these methods inside the `Que.error_notifier` proc to determine whether to submit the error, and if so, what information to send along with it.

The hitch is that the full `job` object is not currently passed to the `Que.error_notifier` proc. Instead, the job's `#que_attrs` are sent as the `job` argument.

Would you consider a PR which changes this argument to be the full job object? I want to check with you before starting the work.

**Comment by chanks** [comment]
Hi Tim, thanks for asking - the issue is that an error might occur before the job can be instantiated (for example, if a job class is renamed and the constantization of an old class name fails, or if somebody overrides the initialize() method and something goes wrong), and the error handler still needs to work in that case. One option would be to yield the instantiated job if it's present or the attributes if it's not, but that pushes some complexity to everyone's handler procs, and requires them to either handle both possible inputs or risk silently losing errors :disappointed:

It seems to me that there are a few other ways you could implement this - you could implement this logic in the error handler proc itself, or encapsulate it in a new class that the error handler proc can use. Or, if it really makes the most sense to keep it in your Que::Job subclass, there's nothing stopping you from instantiating the job class yourself, though you'll probably want to be a little defensive about it (I haven't tested this, I'm just spitballing):

```ruby
Que.error_notifier = proc do |error, attrs|
  job_class =
    begin
      attrs[:job_class].constantize
    rescue NameError
    end

  if job_class
    instance = job_class.new(job_attrs)
    # do things...
  else
    # fall back to the old behavior
  end
end
```

Do any of these seem like reasonable solutions to your problem? Another thing I'd add is that at this level of complexity in the notifier, I think it'd make sense to add unit tests for it.

**Comment by timriley** [comment]
Thanks for the reply Chris, I hadn't thought about those potential issues instantiating the job. Your spitballed solution looks like something I could work with. I'll give it a go!
