### ISSUE TITLE
Any recomended way to run workers in the same process?

### ISSUE THREAD

**Issue by maca** [chanks/que#223]
I've been using Que specifically using whisper. I could use Que.wake! to run the jobs in the same process. I beleave I used concurrent-ruby for dealing with concurrency.

**Comment by chanks** [comment]
Running the workers in your web process hasn't been officially supported for a while, because it tended to trigger runtime issues that were painful to debug. If you want to figure it out on your own, though, you can look at how the CLI instantiates and stops a `Que::Locker` instance, you'll basically want to do that.

Also, `wake!` doesn't exist anymore in 1.0, and it's recommended that you upgrade if you're using 0.x.
