### ISSUE TITLE
Is there something like this gem for NodeJS?

### ISSUE THREAD

**Issue by frederikhors** [chanks/que#228]
This is an amazing job! Really this is gorgeous!

Is there something like this gem for NodeJS that you know?

**Comment by chanks** [comment]
Hi Frederik, not that I know of. If you discover or write one, let me know and we can link to it somewhere in the docs.

**Comment by frederikhors** [comment]
I think this is one: https://github.com/timgit/pg-boss.

I also opened an issue for asking this here: https://github.com/timgit/pg-boss/issues/86

**Comment by frederikhors** [comment]
Isn't it?

**Comment by chanks** [comment]
It seems to use SKIP LOCKED, rather than advisory locks, which makes it somewhat different. It's not immediately clear whether it uses LISTEN/NOTIFY either.

I dunno, in the past when projects have ported Que's design to other languages I've added links to them in the docs (and then removed them in the 1.0 redesign since the changes felt pretty large), but I kind of don't want to go down the road of adding links in the docs to every other Postgres-based queue, regardless of design.

**Comment by frederikhors** [comment]
The truth is that your work is very wonderful and I unfortunately can not use anything other than javascript now. Neither Ruby nor Golang.

For us mere mortals it would be interesting to understand if there is any javascript project that has the same structural design of yours and it would also be interesting to have the links in your Readme.

Please.

Thank you.

**Comment by chanks** [comment]
Thanks, but I don't think people will have a problem finding that project if they want to use a Postgres-based queue from Node. I mean, that's what Google is for. But it doesn't really feel closely related enough that it's worth cluttering up the READMEs of each project with links.
