### ISSUE TITLE
Buffer size of zero does not work

### ISSUE THREAD

**Issue by haimgel** [chanks/que#235]
We're using Que with jobs that take a really long time to complete (hours), and would like to set up Que so that each worker process does not lock more than the one job that it's currently processes.

When we set `minimum_buffer_size` and `manimum_buffer_size` to zero, the workers do not pick any jobs at all. When we set the buffer size to one, the workers start picking up jobs but then they also pick and lock the _next_ job.

Is there any way to configure Que not to lock any jobs beside the one it is currently processing?

**Comment by chanks** [comment]
I just pushed a minor fix to master so that `--minimum_buffer_size 0 --maximum_buffer_size 0` should still pick up enough jobs to satisfy the workers - try it out and let me know if that solves your problem.

(Also master has started failing sometime in the last 10 months, looks like it's due to changes in Rails. I may or may not find time to fix that soon.)

**Comment by chanks** [comment]
Opened issue #236, I'm going to close this one. Thanks for the report!
