### ISSUE TITLE
Question: about forking servers.

### ISSUE THREAD

**Issue by lucasdavila** [chanks/que#238]
Hi @chanks ,

I am switching from passenger to puma on an API that uses que, it was configured to set que mode to async, after passenger started the process, so I checked the que documentation to see what is the equivalent configuration to puma.

But I figured that you removed the part about "Forking Servers" on this commit: https://github.com/chanks/que/commit/fb1ddd99695f361a20f53e3b9829668ed4719837#diff-7184ddc99e52d82b98da9742d9ac2a94L27

So I would like to ask: isn't that configuration needed anymore?

Also it keeps mentioning about "Forking Servers" on the docs readme file.

Thank you.

**Comment by chanks** [comment]
That was removed from the docs because Que stopped explicitly supporting
running in the same process as the webserver, since it kept resulting in
difficult-to-debug issues (with the rails integration, IIRC) - instead the
CLI became the only officially supported way to run jobs. I don’t remember
what version that happened in though (I’m on my phone and can’t easily look
it up right now).

Of course you can still do that if you really want to, and if you did you
would want to only start doing it after the process forks. There’s no
officially-supported mechanism for it, though.

Any leftover mention of forking servers should probably be removed, I
think? I’m not sure why they’d need to be there anymore.

**Comment by lucasdavila** [comment]
Hi @chanks ,

Thank you for the quick response.

I just figured that the API is running on que 0.14.3, which I think is not affected by those changes, so it will continue using the "forking servers" approach, until I update que to the last version.

I will close the issue.
