### ISSUE TITLE
`NOTIFY`/`LISTEN` support?

### ISSUE THREAD

**Issue by abevoelker** [chanks/que#75]
Hello, just found this neat project.  I currently use `queue_classic` to process jobs, which doesn't use advisory locks but does use `NOTIFY`/`LISTEN` for efficiently picking up new jobs.  It looks like `que` currently uses polling to detect new jobs.

I see there has been some consideration for `NOTIFY`/`LISTEN` in #8 and #22 and the "experimental" branch.  Just wondering if that's still a feature being considered?  Polling works fine for my use case, but I'm just curious.  Thanks!

**Comment by joevandyk** [comment]
There was some work to support listen/notify, but it's incomplete, as far as I know. 

Polling is super fast though, and works with connection balancers.

**Comment by abevoelker** [comment]
Thanks, yeah I should be perfectly fine just using polling.  And yeah I see there is an open issue on `queue_classic` in regards to issues w/ pgBouncer: https://github.com/QueueClassic/queue_classic/issues/184

**Comment by chanks** [comment]
The experimental branch (which replaces single-job polling with a mixture of LISTEN/NOTIFY and batch polling) is functional, though out of date with the changes made to master since that time. The main hurdle that's left, I think, is benchmarking to make sure its design works at scale, and to see what kind of improvement (if any?) it gives over master.

I'd like to get back to it at some point, but since I've been busy and master seems to have been fast enough for everyone's purposes, it just hasn't been a priority.

**Comment by abevoelker** [comment]
Thanks for the info!
