### ISSUE TITLE
Check that prepared statements are working as expected.

### ISSUE THREAD

**Issue by chanks** [chanks/que#76]
See #74.

**Comment by joevandyk** [comment]
```
tanga_dev=# prepare test  as select 'now'::timestamptz;
PREPARE
tanga_dev=# execute test;
          timestamptz
-------------------------------
 2015-01-13 09:13:05.742936-08
(1 row)

tanga_dev=# execute test;
          timestamptz
-------------------------------
 2015-01-13 09:13:05.742936-08
(1 row)
```

**Comment by joevandyk** [comment]
Although: 
```
tanga_dev=# prepare test  as select 'now()'::timestamptz;
PREPARE
tanga_dev=# execute test;
          timestamptz
-------------------------------
 2015-01-13 09:20:51.518569-08
(1 row)

tanga_dev=# execute test;
          timestamptz
-------------------------------
 2015-01-13 09:20:51.518569-08
(1 row)
```

I don't know much about prepared statements yet.

**Comment by johto** [comment]
Yeah, the difference is that one is a function call evaluated during runtime, and the other one is a literal evaluated during prepare.  If the problem can't be reproduced in Ruby, I'm guessing it doesn't do server-side prepared statements.

The cast to timestamptz for `now()` is unnecessary, since it's guaranteed to return a timestamptz.

**Comment by chanks** [comment]
Going through old issues and can't replicate this one. I suppose the switch to now() fixed it. Thanks, though!
