### ISSUE TITLE
Optionally using stored procedures

### ISSUE THREAD

**Issue by johto** [chanks/que#79]
The discussion in #77 derailed a bit, so I'm opening a new thread for this.

The idea is to use stored procedures for grabbing an item from the queue to avoid the extra round trip otherwise necessary to deal with the race condition.  I ran some initial tests using a program I wrote just a while back, and the results suggest an improvement in performance:

![Performance Test Results](http://i.imgur.com/khRmTpf.png)

(The program implements the same general algorithm, but it's not exactly the code `Que` uses.)

It's not clear that anyone needs queues this fast (we're already talking thousands of items per second), though, so I'm not sure if this is worth the effort in practice.

**Comment by chanks** [comment]
Thanks! If you're interested in continuing to investigate queuing techniques like this, you might want to look at Que's experimental branch. It replaces the current technique of polling to lock a single job with a mixture of both LISTEN/NOTIFY and locking jobs in batches. I haven't touched the code in a while and never got around to benchmarking it because Que seems plenty fast for people already. And it might be messy, but if you have any questions about it, ping me.

I'll leave this issue open to remind myself to investigate this more at some point. We already have a migration system in place, and the job lock query doesn't change that often, so it may be worth doing.

**Comment by johto** [comment]
> Thanks! If you're interested in continuing to investigate queuing techniques like this, you might want to look at Que's experimental branch.

I'm sorry, but I think this is as far as my interest goes right now.  I just figured I'd take a look since I saw the discussion in the other thread and I just this week built a program for testing different approaches to queues.

**Comment by chanks** [comment]
Ok, thanks again!

**Comment by chanks** [comment]
Closing this to clean up the issue tracker a bit - it's an interesting idea but I don't think it'll help that much with the 1.0 architecture. Thanks again, though!
