### ISSUE TITLE
Move Que::Migrations.transaction method to Que.transaction

### ISSUE THREAD

**Issue by joevandyk** [chanks/que#81]
I was noticing on the recurring jobs example, this is the last line:
```ruby
self.class.enqueue(args, run_at: @run_again_at)
```

It seems like we'd want to do something like this instead, right?
```ruby
Que.transaction do # Instead of Que::Migrations.transaction
  self.class.enqueue(args, run_at: @run_again_at)
  destroy
end
```

Should the transaction method be inside the Que::Migrations module?

**Comment by chanks** [comment]
The re-enqueuing of the job should definitely be in a transaction - we can fix that at some point, but I'm running out the door and will be traveling this weekend. The transaction method is really only to ensure that the migrations run safely - I think we should be encouraging people to use their ORM's transaction machinery instead of ours. I guess it couldn't hurt to make it easier to use for people using bare PG connections without ActiveRecord or Sequel, but I don't know that anybody actually uses Que that way.

**Comment by joevandyk** [comment]
I've been thinking about some common que patterns that we use and will release those as gems shortly (like the cron one).  Hopefully you'd be able to use those gems no matter what connection adapter you are using.

I think that using Que.transaction would be the best option?

**Comment by chanks** [comment]
Yeah, I'm fine with moving it to the Que module so it's more generally
useful for people who need a transaction helper method and don't have one.
I think you'll run into problems if you just use it universally for all
connection adapters (consider what would happen if somebody using Sequel
tried to use DB.transaction in a job you're already wrapping with
Que.transaction - Sequel's BEGIN would raise a warning but work, and
Sequel's COMMIT would work, but then the destroy and re-enqueuing would be
taking place outside a transaction, and I believe the next COMMIT would
raise an error?). But of course it's up to you.

If you want to submit a pull request I'll accept it, or I might be able to
get to it this weekend. Either way I'll want to have a disclaimer in there
about how people should only use it if they're not using an ORM, or if
they're certain they know what they're doing.
