### ISSUE TITLE
Search for job by args.job_id

### ISSUE THREAD

**Issue by xpepermint** [chanks/que#84]
I can't easily query for a job at the moment (added using ActiveJob), because `MyJob.perform_later.job_id` returns `uuid-style` id and not the number of the `job_id` column.

What can we do to make job querying easier?
- Change job_id from `autoincrement` to uuid (used by ActiveJob)?
- Change `json` to `jsonb`, adding index (this would in general be a good idea)?

For now I just do a hack like this:
```ruby
class Job < ActiveRecord::Base
  self.table_name = :que_jobs
  scope :args, ->(hash) { where("args::text LIKE ALL (?)", "{#{hash.collect{|k, v| ("%\\\"#{k}\\\":\\\"#{v}\\\"%") }.join(",")}}") }
end
```

**Comment by chanks** [comment]
I'm don't know why ActiveJob would return a uuid. I haven't looked at it, and with all the incompatibilities people have been reporting, I wouldn't really recommend using it.

To answer your questions, changing the format of the job_id isn't an option, since then there'd be no way to lock jobs if there's no unique integer to use. Changing the args column to jsonb feels like a bad default, since jsonb data tends to be larger than json, and I don't think most people would query on that column. And I don't think it should be configurable, because having the DB structures be dependent on configuration options would make migrations a lot more complex. I don't think it would be that hard to make Que not break if you manually changed the args hash to be jsonb - that appeals to me because Que is meant to be extendable and flexible. But I couldn't guarantee that it'd be supported in the future.

**Comment by marshall-lee** [comment]
Can we rely on `jsonb` at all? it's only for >= 9.4

**Comment by chanks** [comment]
Yes, which is another reason not to make it the default.

I'm going to close this until/unless there's more interest in supporting jsonb as an option, but I'll also add that if you're only interested in querying jobs by a particular value in the args hash, an expression index is probably a better fix for you right now. It'll be something like (from memory, not tested):

```
CREATE INDEX que_jobs_args_job_id ON que_jobs (args->'id');
```

Then you could efficiently query like:

```
SELECT * FROM que_jobs WHERE args->'id' = 89
```
