### ISSUE TITLE
feature: stack queue

### ISSUE THREAD

**Issue by skyeagle** [chanks/que#86]
Hello, @chanks !

We have already patched `que` to have ability manual set a job_id instead of a sequential job_id. It gives us benefits of `stack queue` by a job_id. So, it would be awesome to have it out of the box if it is necessary to someone. But it will change default migration. The job_id column will change its type from `bigserial` to just `bigint`. What are your thoughts about this feature? I could provide a PR if it makes sense.

**Comment by xpepermint** [comment]
Related https://github.com/chanks/que/issues/84.

**Comment by chanks** [comment]
I'm not sure how this would work or what the benefit is, can you tell me more? Or point me towards the fork/patch?

**Comment by joevandyk** [comment]
I think it's so they can have LIFO jobs. I think you could use the priority column for this?

**Comment by chanks** [comment]
That's what I was thinking, but I was having a hard time picturing the use case for it. And I'm wondering how complex it would be to efficiently track a current job_id (or priority for that matter) among all processes that might be queuing jobs.

**Comment by skyeagle** [comment]
For example, our use case:

```ruby
# app/models/file/base.rb

def job_id
   Zlib.crc32 id # id represented as uniq string in our case
end

after_commit :enqueue_jobs
before_destroy :flush_jobs

def enqueue_job
   run_at = Time.now
   [ checksum, :preview, :cloud].each do |job|
     "#{job}_job".classify.constantize.enqueue id, job_id: job_id, run_at: run_at
   end
end

def flush_jobs
    Job.where(job_id: job_id).delete_all
end
```

It this case we will have sequential certain execution order in scope of job_id. And we don't want to implement a state machine for that. Also, we expect that small chance of collisions in generation of crc2 and appropriate job_id doesn't make sense.

**Comment by chanks** [comment]
If you need to perform some actions in a specific order, you're going to want to either put them all in one job or have the first job enqueue the second as it's destroyed, then the second enqueues the third, and so on. From what I can tell, what you've written is going to fail when you try to use it, because the three different jobs will all be processed at the same time by different workers (playing with the job_id may ensure that job #1 is started first, but jobs #2 and #3 won't be far behind. If each job relies on the one before it having finished, you're going to get errors and unpredictable behavior.

**Comment by skyeagle** [comment]
Yes, you are right. I was wrong with the example. In our original code there was no equal run_at and let it be as time now. I'm sorry.

However, as I understand postgresql's locks. if we have certain order (priority, run_at, job_id) and one of the processes takes a job with certain job_id, no one other process could take the same job. Therefore, we will have `stack` queue by job id which one sometimes is necessary.

**Comment by chanks** [comment]
That's true - I assume that you've changed the enqueue method and the job insertion SQL to actually use the job_id you pass? Because otherwise it's simply passing that job_id to the args hash.

Is there a reason you can't simply do all these things sequentially in the same job, or just enqueue the next job as you destroy the previous ones? That would be cleaner than manually assigning duplicate job_ids and relying on your queue's internal locking logic not changing (not that I'm planning for it to change).

**Comment by skyeagle** [comment]
>  the job insertion SQL to actually use the job_id you pass? Because otherwise it's simply passing that job_id to the args hash

Yeap. We have hacked the insertion also. I had to mention this.

> Is there a reason you can't simply do all these things sequentially in the same job.

Definitely. Each job could be really complicated. And it will be hard to test it.

> Is there a reason you can't simply do all these things sequentially in the same job, or just enqueue the next job as you destroy the previous ones? That would be cleaner than manually assigning duplicate job_ids and relying on your queue's internal locking logic not changing (not that I'm planning for it to change).

So, the example was simplified. In real case you have some conditions on job enqueuing to avoid extra inserts and IO operations on DB. For example, preview job appropriates only for thumbnalable files (by content_type) and etc...

**Comment by chanks** [comment]
Alright, I understand. That's an interesting use case, but I think for the vast majority of people who need jobs to run sequentially, simply enqueuing the next job as the previous one finishes (and doing whatever queries are necessary to figure out whether that should be done) will work just fine, so I don't think it's worth complicating the queueing/locking mechanism in order to support it. I'm glad Que was flexible enough to support your use case, though, and thanks for bringing it up.

**Comment by skyeagle** [comment]
It's ok. Thanks for your great work.
