### ISSUE TITLE
Support for not retrying a failed job

### ISSUE THREAD

**Issue by Sinjo** [chanks/que#94]
Que makes the assumption that any failed job should be re-enqueued. There are failure cases where we don't want to keep retrying a job, and right now there's no way of handling them with Que.

To be specific, we only want to retry on errors we consider transient. This usually means connectivity issues, which fall into a known list of exceptions.

If, for example, there's an issue in the job logic which causes the job to fail, we'd rely on our exception tracker to inform us, and intervene manually, then re-enqueue the job.

There's a few options I've thought about to handle this:

* Make the `retry_interval` proc contact our error tracker, and set the job to be retried at timestamp [infinity](http://www.postgresql.org/docs/9.1/static/datatype-datetime.html#AEN5827)
* Modify Que so that it marks the job to not be retried in some way (eg setting `run_at` to `nil`)
* Modify Que so that failed jobs which aren't rescheduled get moved to a different table.

I'd be really interested in hearing your opinions on handling this kind of failure. I'm kind of assuming this is a situation a bunch of people run into.

**Comment by joevandyk** [comment]
Can you rescue the exception in the job, log it somehow, then not re-raise
the exception?

**Comment by Sinjo** [comment]
That gets it into the exception tracker, but doesn't stop Que from automatically retrying it.

**Comment by joevandyk** [comment]
Que will only retry jobs that raise an exception. If you rescue the exception inside the job, Que won't retry the job.

**Comment by Sinjo** [comment]
If I understand right, the job will get destroyed in that case. I'd like it to still exist, otherwise the uptime/storage durability of your exception tracker become way more important.

**Comment by chanks** [comment]
Setting run_at to nil won't be a simple fix, since it's part of the primary key. Setting run_at to infinity might work without modification, but if you accumulated a bunch of them it might slow down the index scan that finds the next available job to lock (not sure about that). You could also inserting it into a separate table as you destroy it, or just set the queue name for the job to "do_not_run" or something like that, and just never run a worker that works on that queue. The separate table is probably the most foolproof?

I don't think it's a very common situation (I think the default of retrying with an exponential backoff makes sense for the vast majority of cases), but I'm curious to hear what you decide and how it works out.

**Comment by joevandyk** [comment]
We set the run_at to 10 years in the future for some things that we want to
manually rerun if needed.

**Comment by chanks** [comment]
This is more of a discussion topic than an issue, so I'm going to close it. Feel free to bring it up in the new google group: https://groups.google.com/forum/#!forum/que-talk

**Comment by 9mm** [comment]
@joevandyk  i know this post is super old but do you remember how you did that? I'm trying to make it not retry on failure. I have tried the skipretry method but it doesnt actually log the error, so its kind of useless
